name: build

on:
  pull_request:
    branches: [ master, development ]

jobs:
  tsc:
    name: TypeScript Compile Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install node v12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: yarn install
      run: yarn install
    - name: tsc
      uses: icrawl/action-tsc@v1
    - uses: actions/checkout@v1
    - name: install node v12
      uses: actions/setup-node@v1
    - name: Install
      run: npm install
    - name: Lint
      run: npm run lint
    - name: Unit Test
      run: npm run test
